language: python
os: linux
dist: bionic
cache: pip

python:
  - '3.8'
  - '3.7'
  - '3.6'
  - 'pypy3'
  - 'nightly'

env:
  - MAKE_TARGET=test

jobs:
  include:
    - python: '3.8'
      env: MAKE_TARGET=lint
    - python: '3.8'
      env: MAKE_TARGET=coverage
  allow_failures:
    - python: 'nightly'

install:
  - |
    if [ "$MAKE_TARGET" = "coverage" ]; then
      pip install coveralls
    fi
  - pip install --upgrade -r requirements.txt -e .

script:
  - make "$MAKE_TARGET"

after_success:
  - |
    if [ "$MAKE_TARGET" = "coverage" ]; then
      coveralls
    fi
