language: python

python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3

matrix:
  allow_failures:
    python: pypy3

install:
  - pip install -r requirements-dev.txt

script: py.test --flake8
